version: '3.8'
services:
   mongodb :
      image : mongo
      container_name : mongodb
      ports :
         - "27017:27017"
      volumes:
         - newvolume:/data/db
 
   backend:
      build: .
      # image: backend
      container_name : backend
      ports : 
        - "3000:3000"
      depends_on:
        - mongodb
      environment: 
          MONGO_URL:  "mongodb://mongodb:27017/todo"

volumes:
  newvolume:           